export enum OrderPaymentMethodEnum {
  Card = "card",
  BankTransfer = "ach_credit_transfer",
  Ideal = "ideal",
  Alipay = "alipay",
  Bancontact = "bancontact",
  Eps = "eps",
  giropay = "giropay",
  klarna = "klarna",
  multibanco = "multibanco",
  sepa_debit = "sepa_debit",
  sofort = "sofort",
  wechat_pay = "wechat_pay",
  p24 = "p24",
  paypal = "paypal",
  afterpay_clearpay = "afterpay_clearpay",
}
